### ISSUE TITLE
registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

### ISSUE THREAD

**Issue by ghost** [phonegap-build/PushPlugin#307]
We tested our app in iOS 8 and Push Notifications do not work. Notifications work in iOS 7 and iOS 6.

Two issues were identified:

1) Repeated occurrence of error: registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

2) After some time, the app crashes:  

malloc: **\* mach_vm_map(size=135168) failed (error code=3)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug

**Comment by vtntimo** [comment]
@rossmartin @mawfluke is this problem still current? I tried to register an iOS8 device with both phonegap-build's PushPlugin and the @rossmartin version, but I get no callbacks - no success, no error, no nothing :O

**Comment by rossmartin** [comment]
@vtntimo Yeah this issue still exists.  My commit that fixes this issue was on Nov. 2 and the last commit  in the official repo was October 3rd.  I've been using my own fork for the last 3 months.

**Comment by vtntimo** [comment]
@rossmartin okay, thanks for clearing this out. My code doesn't seem to
launch the callbacks at all, but I guess that is a separate issue.

**Comment by brahmikumar** [comment]
Notification not working in iOS 8.1.3 version in iPhone 6, 
but it working in iOS 8.1.1 version in iPhone 5.

**Comment by brahmikumar** [comment]
Notification not working in iOS 8.1.3 version in iPhone 6, 
but it working in iOS 8.1.1 version in iPhone 5.

**Comment by brahmikumar** [comment]
Notification not working in iOS 8.1.3 version in iPhone 6, 
but it working in iOS 8.1.1 version in iPhone 5.

**Comment by brahmikumar** [comment]
Notification not working in iOS 8.1.3 version in iPhone 6, 
but it working in iOS 8.1.1 version in iPhone 5.

**Comment by brahmikumar** [comment]
Notification not working in iOS 8.1.3 version in iPhone 6, 
but it working in iOS 8.1.1 version in iPhone 5.

**Comment by Himanshu7441** [comment]
@brahmikumar Same issue is happening with me. Notification not worling in iPhone 6, but its working in iPhone 5,iPhone 5s, iPhone 4s...
Any idea why??

**Comment by brahmikumar** [comment]
My issue is solved, after updating latest version push plugin my issue solved,
Now i'm getting notification in iOS 8.3 version device also.I'm using this push plugin.
https://github.com/phonegap-build/PushPlugin/blob/1979d97/README.md

**Comment by Himanshu7441** [comment]
@brahmikumar I have also used the same plugin and i am also using the latest iOS version but the issue still persits..
