### ISSUE TITLE
PushPlugin Not working

### ISSUE THREAD

**Issue by crookedcircle** [phonegap-build/PushPlugin#611]
Having issues in testing this code on Phonegap Build.. 
Has anything changed lately? a few months it was working perfectly fine.. 
When I add a config.xml file in the Example/www folder and upload it on Phonegap Build 
This is what I have added in config.xml

    <feature name="PushNotification" >	
    	<gap:plugin name="com.phonegap.plugins.pushplugin" version="2.5.0" />
    </feature>

Is anyone else also facing the same issue?? Please help..

**Comment by MaicolBen** [comment]
The same happens to me, but 2.4.0 works.

More info at [Phonegap Build Forum](http://community.phonegap.com/nitobi/topics/error-build?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply[id]=15942548#reply_15942548)

**Comment by amirudin** [comment]
+1 
Release 2.5.0 incompatible with PhoneGap Build for Android as well. Most probably caused by https://github.com/phonegap-build/PushPlugin/pull/588

**Comment by sicter** [comment]
+1

**Comment by nikolaid8** [comment]
+1
Can't build Android app with 2.5.0, but 2.4.0 working

**Comment by jdinse** [comment]
+1

**Comment by macdonst** [comment]
This problem should be fixed on PhoneGap Build as well as we pushed a new release to build.

**Comment by idanbezalel** [comment]
How can I download 2.4.0 ? 
I want stable version for my cordova project .

(I still dont understand why Push notification its not a Core Plugin in cordova project ...)

**Comment by jdinse** [comment]
If you want to download it as zip or tar.gz, you 'll find the files at the releases-tab of this repository:
https://github.com/phonegap-build/PushPlugin/releases

If you like to include it the url of the git-repository of this release, attach the version as an anchor at the end of repository url:
https://github.com/phonegap-build/PushPlugin.git#2.4.0

**Comment by idanbezalel** [comment]
Verified , 2.5.0 doesn't works in cordova project , 2.4.0 works like a charm .

**Comment by jokabuyasina** [comment]
true !
