### ISSUE TITLE
iOS ecb callback not firing with PushNotification plugin 

### ISSUE THREAD

**Issue by aaroncraigongithub** [phonegap-build/PushPlugin#68]
I've done a full write up of the problem on the PG Build forum, as I assumed to begin with that this was an issue with Build.

They have directed me to post an issue here, though, so here you go :)

http://community.phonegap.com/nitobi/topics/ios_ecb_callback_not_firing_with_pushnotification_plugin

The summary of the post is:
Using more or less the boilerplate example, everything works as expected on Android.  iOS calls the token handler, but does not call the ecb callback.  If the app is in the background the notice is displayed in the notification area or the lock screen on iOS, but activating the app still doesn't cause the ecb handler to run.

**Comment by JeremyColton** [comment]
I am using PG 3.6.3 on iOS7, PushPlugin 2.4.0 and my app behaves as follows:

a) app is running and in the foreground ie open, it receives the notification.
b) app is running but in the background, it does NOT receive the notification!

How can I check if the phone is receiving the notification but ignoring it? Where are the logs?  My XCode console shows activity on the phone but I don't see anything for use case b) above...

**Comment by t2wu** [comment]
@Mechanicalee  You are right about when user pressing the icon, but not the notification message, the app would not be aware of the notification. However, that was before silent notification was introduced or without using silent notification after iOS7. I think PushPlugin could have supported silent notification by implementing `application:didReceiveRemoteNotification:fetchCompletionHandler`. But as it currently stand, it doesn't.

**Comment by allisok** [comment]
hi, i have the same problem, when my app is in foreground and push has come,
there is nothing happening, but in xcode concole i see that push was received.

when my app in background the push come to phone,
but callback function is not fired!

cordova 3.7 , push plugin 2.4.0, ios 7+

**Comment by t2wu** [comment]
@allisok  Send a silent push notification. More details here. http://hayageek.com/ios-silent-push-notifications/ . Watch the WWDC  video on silent push (came out two years ago for iOS7) if necessary.

Also patch the PushPlugin as instructed in this issue: 
https://github.com/phonegap-build/PushPlugin/issues/288

Now, as long as your app is not terminated and is running in the background, it gets awaken for a short period and you can process the message.

**Comment by allisok** [comment]
thank, but i need do some action, when user click on push message,
instead of moment ,when push come. i try send silent push, but when app in foreground
callback isn't firing

**Comment by t2wu** [comment]
@allisok  Not sure what you mean by "user click on push message instead of moment". Anyway, it works for me hwne app is in the background. Provided you patch it like the poster says on issue #288.

**Comment by mmacmillan** [comment]
@rdbmax I can duplicate this behavior if i add a field containing an array to the message payload.  For example, with the following message payload, using [actions](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW26), from [this example](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) will cause the plugin to receive the notification event, but not call the javascript handler:
```
{
    aps: { 
        alert: {
            body: 'test message!',
            actions: [
                { id: 'test-action-id', title: 'test-action' }
            ]
        }
    }
}
```
I am determining the plugin receives the notification event, by receiving the following console output in xcode:
```
2015-02-27 08:33:39.942 PushNotificationsTest[291:79047] Notification received
2015-02-27 08:33:39.943 PushNotificationsTest[291:79047] Msg: {"actions":"(
        {
        id = "test-action-id";
        title = "test-action";
    }
)","body":"test message!","action-loc-key":"View",foreground:"0"}

```
If I remove the `actions` field from the message payload, my app's javascript handler will be fired as expected.  On a side note, it looks like @arzynik added #495 to introduce support for actions, which use arrays, but i haven't tested this myself.

**Comment by clarklight** [comment]
This is 2015 April, i am facing the same problem on Android, i am wondering if this has been fixed?? I click on the Icon, then my notification tray gets deleted, but no ECB is fired.

**Comment by JWesorick** [comment]
+1 Experiencing same behavior as @mmacmillan

**Comment by aBuder** [comment]
+1 Experiencing same behavior as @mmacmillan  an @JWesorick

**Comment by clarklight** [comment]
@aBuder @JWesorick I am wondering if you are talking about that onResume issue, that it does not pull in the push notification into the App,(No ECB when onResume). As i am facing that problem, i read that on version 2.4.0 thats not an issue anymore. But i dont seem to read anywhere on documentation about how to handle onResume(either by clicking the App icon, or from Android).

**Comment by gopaulo** [comment]
+1 Experiencing same behavior as @mmacmillan an @JWesorick and @aBuder

**Comment by IqraRastee** [comment]
+1 Experiencing same behavior

**Comment by mrameezraja** [comment]
Try making your ecb callbacks global for ios and android. i.e
window.onNotificationAPN = function(){ ... }
window.onNotification = function(){ ... }

**Comment by farshidbeheshti** [comment]
> Try making your ecb callbacks global for ios and android. i.e
> window.onNotificationAPN = function(){ ... }
> window.onNotification = function(){ ... }

Yeah, it should solve it!

Farshid

**Comment by SanchoCK** [comment]
> window.onNotificationAPN = function(){ ... }
You are genius! Thanks, this works on iOS for me.

**Comment by fahimehr** [comment]
Making it a global function doesn't fix the issue for me. any other solution?

**Comment by mrameezraja** [comment]
Can you share your code ?

**Comment by addityasingh** [comment]
I have found the solution for this one. The reason for this issue is that in `PushPlugin.m` the `callback` property is set to `nil` on killing the app. As a result, the check on [line#202](https://github.com/phonegap-build/PushPlugin/blob/master/src/ios/PushPlugin.m#L202) is not satisfied in the `- (void)notificationReceived` callback. The fix for the issue is to instantiate the `PushPlugin` class on opening the push notification every time your app starts. This can be done by registering the push notification plugin on app start. 
Call the `pushNotification.register` method in your javascript everytime your app starts, and this will instantiate the plugin and assign the appropriate `callback` the plugin. I have added the below code to my `Ionic` app's `app.run()` section

``` javascript
window.plugins.pushNotification.register(successCallback, errorCallback, {
        badge: 'true',
        sound: 'true',
        alert: 'true',
        ecb: 'window.onNotificationAPN'
})
```

Let me know if anyone still faces this issue.

**Comment by lampofdrog** [comment]
@mrameezraja ur solution fixed the problem thx !
